# Generated by Django 2.2.1 on 2020-04-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passgen', '0002_auto_20200403_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passmodel',
            name='uniquenumber',
            field=models.CharField(default=201301, max_length=10000),
        ),
    ]
