# Generated by Django 2.2.1 on 2020-04-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passgen', '0003_auto_20200403_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='passmodel',
            name='checked',
            field=models.BooleanField(default=0),
        ),
    ]
