# Generated by Django 3.0.5 on 2020-04-02 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('vehiclenumber', models.CharField(max_length=200, null=True)),
                ('phonenumber', models.IntegerField(null=True)),
                ('aadharcardnumber', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('reason', models.CharField(max_length=200, null=True)),
                ('issuedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('passcategory', models.CharField(choices=[('Essential Services Pass', 'Essential Services Pass'), ('Emergency Services Pass', 'Emergency Services Pass')], max_length=30)),
                ('subcategory', models.CharField(choices=[('ATM/Banking', 'ATM/Banking'), ('Delivery Worker', 'Delivery Worker'), ('Fruit/Vegetable Vendor', 'Fruit/Vegetable Vendor'), ('Govt Officials', 'Govt Officials'), ('Grocery Vendor', 'Grocery Vendor'), ('Milk Vendor', 'Milk Vendor'), ('Health Worker', 'Health Worker'), ('IT/Tele Communication', 'IT/Tele Communication'), ('Municipal Services', 'Municipal Services'), ('Power/Electricity', 'Power/Electricity'), ('Sanitation', 'Sanitation'), ('Businessman', 'Businessman')], max_length=30)),
                ('attachphoto', models.ImageField(upload_to='profile_pics')),
                ('attachidproof', models.ImageField(upload_to='id_proof')),
            ],
        ),
    ]
