# Generated by Django 2.2.1 on 2020-04-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passmodel',
            name='uniquenumber',
            field=models.CharField(default=201301, max_length=2000),
        ),
        migrations.AlterField(
            model_name='passmodel',
            name='aadharcardnumber',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='passmodel',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
